### ISSUE TITLE
ender backpack recipe crafts into a normal backpack

### ISSUE THREAD

**Issue by RedBowze** [kwpugh/simple_backpack_fabric#4]
1.21 version
![image_2024-06-16_151452110](https://github.com/kwpugh/simple_backpack_fabric/assets/173003519/49d1026b-6a81-4421-b2ea-8d0dcdac8800)

**Comment by kwpugh** [comment]
seems the vanilla chests tag also includes enderchests.  will fix.

**Comment by RedBowze** [comment]
tysm!!
