### ISSUE TITLE
1.21

### ISSUE THREAD

**Issue by marcelopinheiromocellin** [kwpugh/simple_backpack_fabric#5]
It won't let me create the backpack, it looks like it exists when looking at Jei, but it doesn't create it. Note: THIS HAPPENS ON THE MULTIPLAYER SERVER

**Comment by marcelopinheiromocellin** [comment]
> Não deixa eu criar a mochila, parece que ela existe olhando para o Jei, mas não cria. Obs: ISSO ACONTECE NO SERVIDOR MULTIJOGADOR

**Comment by kwpugh** [comment]
I assume you figured it out?  Mod not on the server and client both?

**Comment by marcelopinheiromocellin** [comment]
> Presumo que você descobriu? O mod não está no servidor e no cliente?

Yes, it is there but it still doesn't work
