### ISSUE TITLE
1.21 recipe issue?

### ISSUE THREAD

**Issue by marcelopinheiromocellin** [kwpugh/simple_backpack_fabric#6]
It works for servers, because on mine it doesn't let you craft it, it even shows in the JEI mod, but it doesn't let you craft it

**Comment by marcelopinheiromocellin** [comment]
![2024-06-24_21 38 40](https://github.com/kwpugh/simple_backpack_fabric/assets/53199000/5426cbe1-8665-4365-b5d8-0d6bbfafb8d2)

**Comment by kwpugh** [comment]
do you have the mod on the server and the clients?

I check my server and works fine.
![Screenshot 2024-06-24 at 10 04 45 PM](https://github.com/kwpugh/simple_backpack_fabric/assets/8809210/5b7565c8-e110-445b-8ff8-748fd969cfe0)

**Comment by kwpugh** [comment]
What version of backpacks are you using?

**Comment by marcelopinheiromocellin** [comment]
hi, I have it in both, in the last version this

> Qual versão de mochila você está usando?

**Comment by marcelopinheiromocellin** [comment]
![image](https://github.com/kwpugh/simple_backpack_fabric/assets/53199000/599d820b-23b5-42ea-ba84-6c4ea3d51e48)
![image](https://github.com/kwpugh/simple_backpack_fabric/assets/53199000/8024df0f-8be4-4d51-9b3d-2e0378f6a988)

**Comment by kwpugh** [comment]
I don't know what to tell you, it works fine on my server.  Are you running any mods that change the vanilla chest, iron ingots, or wool blocks?

**Comment by marcelopinheiromocellin** [comment]
I think it's some permission from the server, because in singlepayer it works normally

**Comment by kwpugh** [comment]
Let me know what you find

**Comment by marcelopinheiromocellin** [comment]
![image](https://github.com/kwpugh/simple_backpack_fabric/assets/53199000/449370ff-49c4-47f9-8e46-a20653c16f91)
this


> Deixe-me saber o que você encontrou

**Comment by kwpugh** [comment]
Simple Backpack does not add a separate data pack, so that is not a problem

are you running polymer on the server?

**Comment by marcelopinheiromocellin** [comment]
> Simple Backpack não adiciona um pacote de dados separado, então isso não é um problema
> 
> você está executando o polímero no servidor?

sorry what would be a polymer on the server?

**Comment by marcelopinheiromocellin** [comment]
Do I have to have this mod on the server?
![image](https://github.com/kwpugh/simple_backpack_fabric/assets/53199000/574ca620-35c7-48b6-825c-b3ab94adbf6f)

**Comment by kwpugh** [comment]
No, It was just a question.

**Comment by marcelopinheiromocellin** [comment]
I don't have this mod on the server

**Comment by kwpugh** [comment]
from the looks of your screenshot, you have two different version of fabric on the client

**Comment by kwpugh** [comment]
if you haven't figured this out you can come to the Discord for further discussion.
